import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "var(--md-background)",
        surface: "var(--md-surface)",
        "surface-dim": "var(--md-surface-dim)",
        "surface-bright": "var(--md-surface-bright)",
        "surface-container-lowest": "var(--md-surface-container-lowest)",
        "surface-container-low": "var(--md-surface-container-low)",
        "surface-container": "var(--md-surface-container)",
        "surface-container-high": "var(--md-surface-container-high)",
        "surface-container-highest": "var(--md-surface-container-highest)",
        "on-surface": "var(--md-on-surface)",
        "on-surface-variant": "var(--md-on-surface-variant)",
        "on-background": "var(--md-on-background)",
        "inverse-surface": "var(--md-inverse-surface)",
        "inverse-on-surface": "var(--md-inverse-on-surface)",
        outline: "var(--md-outline)",
        "outline-variant": "var(--md-outline-variant)",
        primary: "var(--md-primary)",
        "primary-container": "var(--md-primary-container)",
        "on-primary": "var(--md-on-primary)",
        "on-primary-container": "var(--md-on-primary-container)",
        "primary-fixed": "var(--md-primary-fixed)",
        "primary-fixed-dim": "var(--md-primary-fixed-dim)",
        "on-primary-fixed-variant": "var(--md-on-primary-fixed-variant)",
        secondary: "var(--md-secondary)",
        "secondary-container": "var(--md-secondary-container)",
        "on-secondary": "var(--md-on-secondary)",
        "on-secondary-container": "var(--md-on-secondary-container)",
        "secondary-fixed": "var(--md-secondary-fixed)",
        "secondary-fixed-dim": "var(--md-secondary-fixed-dim)",
        "on-secondary-fixed-variant": "var(--md-on-secondary-fixed-variant)",
        tertiary: "var(--md-tertiary)",
        "tertiary-container": "var(--md-tertiary-container)",
        error: "var(--md-error)",
        "on-error": "var(--md-on-error)",
        "error-container": "var(--md-error-container)",
        "on-error-container": "var(--md-on-error-container)",
        warning: "var(--md-warning)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        h1: ["Inter"], h2: ["Inter"], "body-lg": ["Inter"], "body-md": ["Inter"],
        "label-caps": ["Inter"], "display-price": ["Inter"], "display-price-mobile": ["Inter"],
      },
      fontSize: {
        h1: ["22px", { lineHeight: "28px", fontWeight: "700", letterSpacing: "-0.01em" }],
        h2: ["17px", { lineHeight: "24px", fontWeight: "600", letterSpacing: "-0.005em" }],
        "body-lg": ["14.5px", { lineHeight: "21px", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["10.5px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-price": ["28px", { lineHeight: "34px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "display-price-mobile": ["24px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      spacing: {
        "base-unit": "4px",
        "touch-target-min": "44px",
        "container-padding": "20px",
        container: "20px",
        gutter: "12px",
        section: "24px",
        "section-gap": "24px",
      },
      borderRadius: { DEFAULT: "0.375rem", lg: "0.625rem", xl: "0.875rem", "2xl": "1.125rem", "3xl": "1.5rem", full: "9999px" },
      boxShadow: {
        card: "0 1px 4px rgba(0,0,0,0.03), 0 2px 8px rgba(0,0,0,0.04)",
        "card-hover": "0 2px 8px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.05)",
      },
    },
  },
  plugins: [],
} satisfies Config;
