-- ============================================================================
-- Herbaspace POS — Model Keamanan / Isolasi Tenant
-- ============================================================================
-- CATATAN PENTING: file ini SENGAJA tidak berisi DDL yang bisa dijalankan.
-- Menjalankannya adalah no-op (semuanya komentar). Aman.
--
-- Kenapa? Isolasi antar-tenant di aplikasi ini TIDAK bergantung pada Postgres
-- Row Level Security (RLS). Ada dua alasan arsitektural:
--
--   1. Koneksi DB (db/index.ts) memakai POSTGRES_URL / SUPABASE_DB_URL — sebuah
--      koneksi Postgres langsung dengan role berprivilese (pooler/owner). Role
--      seperti ini MEM-BYPASS RLS. Policy apa pun tidak akan diterapkan.
--
--   2. Kode ini mengakses DB lewat postgres.js + Drizzle, BUKAN lewat lapisan
--      PostgREST/Auth Supabase. Fungsi `auth.uid()` (yang dipakai policy RLS
--      Supabase) hanya terisi pada koneksi ber-JWT via Supabase; pada koneksi
--      langsung ia NULL. Jadi policy berbasis `auth.uid()` pasti gagal cocok.
--
-- Versi lama file ini menargetkan tabel yang tidak ada di skema (organizations,
-- users, org_id, raw_materials, inventory, recipes). Skema sebenarnya memakai
-- tenants, profiles, tenant_id, ingredients, recipe_items. Policy lama itu tidak
-- pernah ter-apply (ALTER TABLE organizations langsung error) — dihapus agar
-- tidak menimbulkan rasa aman palsu.
--
-- ----------------------------------------------------------------------------
-- DI MANA ISOLASI TENANT SEBENARNYA DIJAGA?
-- ----------------------------------------------------------------------------
-- Di lapisan aplikasi (serverless API), pada SETIAP handler:
--   * api/_lib/auth.ts — authenticate() memverifikasi JWT Supabase, memuat
--     profil, dan menetapkan auth.tenantId + auth.role. X-Outlet-Id divalidasi
--     milik tenant. requireRole() menjaga endpoint manajemen.
--   * Setiap query di api/_handlers/*.ts menyertakan `WHERE tenant_id = auth.tenantId`
--     (baca maupun tulis). Fungsi DB create_sale menerima p_tenant_id eksplisit.
-- Audit keamanan 2026-07-28 memverifikasi scoping ini ada di semua handler.
--
-- ----------------------------------------------------------------------------
-- KALAU SUATU SAAT INGIN RLS SEBAGAI PERTAHANAN BERLAPIS (defense-in-depth)
-- ----------------------------------------------------------------------------
-- Itu perubahan arsitektur, BUKAN sekadar menulis policy:
--   1. Ganti koneksi ke sesi ber-otentikasi per-request (mis. set
--      `request.jwt.claims` / `SET LOCAL app.tenant_id = <tenant>` di awal tiap
--      transaksi), dan pakai role DB yang TIDAK mem-bypass RLS.
--   2. Baru tulis policy terhadap tabel NYATA (tenants/profiles/tenant_id) yang
--      membandingkan tenant_id dengan tenant di sesi.
-- Menyalakan RLS tanpa langkah (1) berisiko: kalau role-nya bypass → tidak ada
-- efek (aman palsu); kalau tidak → SEMUA query bisa terblokir dan app mati.
-- Karena itu jangan ada ENABLE ROW LEVEL SECURITY di sini.
-- ============================================================================
